-- Verificar que estamos en la BD correcta -- 
SELECT current_database();
-- Debe retornar: tiendalatam

-- Tabla paises 
CREATE TABLE paises(
pais_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
codigo_pais VARCHAR (2) NOT NULL,
nombre_pais VARCHAR (15) NOT NULL,
continente TEXT NOT NULL
); 

-- Tabla de catergorias 
CREATE TABLE categorias(
categoria_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre_categoria TEXT NOT NULL, 
descripcion TEXT NOT NULL
); 

CREATE TABLE tipos_clientes(
tipo_cliente_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre_tipo VARCHAR (12) NOT NULL,
descripcion TEXT NOT NULL
);

CREATE TABLE sucursales(
sucursal_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre_sucursal TEXT NOT NULL,
ciudad TEXT NOT NULL,
pais_id INTEGER NOT NULL REFERENCES paises(pais_id),
direccion_completa TEXT NOT NULL,
activo BOOLEAN NOT NULL DEFAULT TRUE 
);

CREATE TABLE empleados(
empleado_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre VARCHAR (15) NOT NULL,
apellido VARCHAR (15) NOT NULL,
email VARCHAR (50) NOT NULL UNIQUE,
sucursal_id INTEGER NOT NULL REFERENCES sucursales(sucursal_id),
fecha_ingreso DATE NOT NULL DEFAULT CURRENT_DATE,
cargo TEXT NOT NULL,
activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE clientes(
cliente_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre VARCHAR (15) NOT NULL,
apellido VARCHAR (15) NOT NULL,
email VARCHAR (50) NOT NULL UNIQUE,
telefono VARCHAR (20),
pais_id INTEGER NOT NULL REFERENCES paises(pais_id),
ciudad TEXT NOT NULL,
tipo_cliente_id INTEGER NOT NULL REFERENCES tipos_clientes(tipo_cliente_id),
fecha_registro DATE NOT NULL DEFAULT CURRENT_DATE,
activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE productos(
producto_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
codigo_producto VARCHAR (20) NOT NULL,
nombre_producto TEXT NOT NULL,
categoria_id INTEGER NOT NULL REFERENCES categorias(categoria_id),
precio NUMERIC (15,2) NOT NULL,
stock VARCHAR (10) NOT NULL,
descripcion TEXT NOT NULL,
activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE pedidos(
pedido_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
cliente_id INTEGER NOT NULL REFERENCES clientes(cliente_id),
sucursal_id INTEGER NOT NULL REFERENCES sucursales(sucursal_id),
empleado_id INTEGER NOT NULL REFERENCES empleados(empleado_id),
fecha_pedido TIMESTAMP NOT NULL DEFAULT CURRENT_DATE,
estado VARCHAR (15) NOT NULL,
total NUMERIC (15,2) NOT NULL,
notas TEXT
);

CREATE TABLE detalles_pedidos(
detalle_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
pedido_id INTEGER NOT NULL REFERENCES pedidos(pedido_id),
producto_id INTEGER NOT NULL REFERENCES productos(producto_id),
cantidad VARCHAR (10) NOT NULL,
precio_unitario NUMERIC (15,2)
);
